# SPDX-FileCopyrightText: Contributors to fl-base-pack
# SPDX-License-Identifier: MIT
"""Convex solid primitives that build into a bmesh. Requires Blender (bmesh, mathutils).

`loft.panel` builds a LIFTING SURFACE from an airfoil section — the right primitive for a wing and
the wrong one for a truck. These are the blunt shapes: boxes, tapered boxes, cylinders. Ground
vehicles, storage tanks and gun barrels are made of them, and they were the missing half of this
library the first time the pack had to build something that does not fly (fl-base-pack#17).

Axes match the rest of the library and the engine: nose +X, up +Z, starboard -Y (Blender space;
the glTF exporter maps it).

DETERMINISM. Every ring here is generated by an explicit `range`, never by iterating a set or a
dict, and no primitive touches a random source. The pack regenerates its meshes byte-for-byte as a
regression check (tools/meshlib/README.md) and these must not be the thing that breaks it.
"""

# ⚠ `import bpy` FIRST, AND IT IS NOT DEAD CODE. Under Blender-as-a-module (the `bpy` wheel the
# determinism CI job installs) NEITHER `bmesh` NOR `mathutils` exists until `bpy` has initialised
# the embedded Blender — a module-scope `from mathutils import ...` in a file imported before bpy
# raises ModuleNotFoundError and the build dies before it starts. `loft` gets away without this
# line only because every caller happens to import bpy first; the ground-unit builders enter
# through this module instead, and CI found it twice (once for bmesh, once for mathutils) on a box
# where a real Blender binary builds all four units perfectly. State the dependency, do not rely on
# import order elsewhere.
import bpy  # noqa: F401
import bmesh
from mathutils import Matrix, Vector

from .curves import circle_points

# Cross-section plane for each extrusion axis: which two world axes the (u, v) section maps onto.
_SECTION_AXES = {"x": (1, 2), "y": (0, 2), "z": (0, 1)}
_AXIS_INDEX = {"x": 0, "y": 1, "z": 2}


def rect_section(width: float, height: float):
    """A rectangular cross-section, counter-clockwise in the (u, v) plane. Pure math."""
    hw, hh = width * 0.5, height * 0.5
    return [(-hw, -hh), (hw, -hh), (hw, hh), (-hw, hh)]


def _ring(bm, section, axis, along, center):
    """One ring of verts: a planar cross-section placed at `along` on `axis`, offset by `center`."""
    ai = _AXIS_INDEX[axis]
    ui, vi = _SECTION_AXES[axis]
    verts = []
    for (u, v) in section:
        p = [0.0, 0.0, 0.0]
        p[ai] = along
        p[ui] = u
        p[vi] = v
        verts.append(bm.verts.new(Vector((p[0] + center[0], p[1] + center[1], p[2] + center[2]))))
    return verts


def solid(bm, section_a, section_b, axis="x", a=0.0, b=1.0, center=(0.0, 0.0, 0.0), caps=True):
    """Bridge two equal-length cross-sections into a closed convex solid.

    `section_a`/`section_b` are (u, v) point lists of the SAME length — that is what makes a
    tapered box and a cone the same operation as a box. `a`/`b` are the positions of the two
    sections along `axis`; `center` translates the whole solid.

    Face winding is not fussed over here: `recalc_normals` at the end of a build fixes the lot in
    one deterministic pass, which is far less error-prone than getting the order right per solid.

    Returns every vert it created, in creation order, so the caller can hand the whole solid to
    `rotate` — which is how anything that is not axis-aligned (an elevated launcher rail, a
    depressed gun barrel) gets built out of axis-aligned parts.
    """
    if len(section_a) != len(section_b):
        raise ValueError("solid() needs two sections of the same length")
    ring_a = _ring(bm, section_a, axis, a, center)
    ring_b = _ring(bm, section_b, axis, b, center)
    n = len(ring_a)
    for i in range(n):
        j = (i + 1) % n
        try:
            bm.faces.new((ring_a[i], ring_a[j], ring_b[j], ring_b[i]))
        except ValueError:
            pass  # a degenerate edge where a section collapses to a point (a cone tip)
    if caps:
        for ring in (ring_a, ring_b):
            try:
                bm.faces.new(ring)
            except ValueError:
                pass
    return ring_a + ring_b


def box(bm, center, size, axis="x"):
    """An axis-aligned box centred on `center` with (x, y, z) extents `size`."""
    ai = _AXIS_INDEX[axis]
    ui, vi = _SECTION_AXES[axis]
    section = rect_section(size[ui], size[vi])
    half = size[ai] * 0.5
    return solid(bm, section, section, axis, -half, half, center)


def taper(bm, center, size_a, size_b, length, axis="x"):
    """A box whose two ends differ: `size_a`/`size_b` are (u, v) extents of each end section.

    A vehicle hull with a sloped glacis, a gun barrel that steps down, a berm — all one call.
    """
    half = length * 0.5
    return solid(bm, rect_section(*size_a), rect_section(*size_b), axis, -half, half, center)


def cylinder(bm, center, radius, length, axis="z", segments=16, radius_b=None):
    """A cylinder (or a truncated cone when `radius_b` differs) centred on `center`.

    `segments` is the only knob that changes the triangle count, and it is an explicit parameter
    rather than a constant because a storage tank the player flies past at 300 kt and a road wheel
    that is four pixels wide do not deserve the same budget.
    """
    rb = radius if radius_b is None else radius_b
    half = length * 0.5
    return solid(bm, circle_points(radius, segments), circle_points(rb, segments),
                 axis, -half, half, center)


def rotate(bm, verts, angle_rad, axis=(0.0, 1.0, 0.0), pivot=(0.0, 0.0, 0.0)):
    """Rotate `verts` about `pivot` — the one operation these axis-aligned primitives cannot do.

    Build the part where it is easy to reason about (a missile lying along +X at the origin), then
    put it where it belongs. Deterministic: a fixed matrix applied to a caller-ordered vert list.
    """
    bmesh.ops.rotate(bm, verts=verts, cent=Vector(pivot),
                     matrix=Matrix.Rotation(angle_rad, 3, Vector(axis)))
    return verts


def recalc_normals(bm) -> None:
    """Point every face outward. Call once, after all solids are built, before `finish_mesh`."""
    bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
