# SPDX-FileCopyrightText: Contributors to fl-base-pack
# SPDX-License-Identifier: MIT
"""Pure-math tests for the curves module. No Blender required."""

import math

from fl_meshlib.curves import circle_points, lerp, smoothstep


def test_smoothstep_endpoints_and_midpoint():
    assert smoothstep(0.0) == 0.0
    assert smoothstep(1.0) == 1.0
    assert math.isclose(smoothstep(0.5), 0.5)


def test_smoothstep_clamps():
    assert smoothstep(-3.0) == 0.0
    assert smoothstep(3.0) == 1.0


def test_smoothstep_is_flat_at_ends():
    # Zero first derivative at both ends is what makes it "smooth"; approximate numerically.
    eps = 1e-6
    assert smoothstep(eps) < eps          # slope ~0 near 0
    assert (1.0 - smoothstep(1.0 - eps)) < eps


def test_lerp_uses_eased_parameter():
    assert lerp(10.0, 20.0, 0.0) == 10.0
    assert lerp(10.0, 20.0, 1.0) == 20.0
    assert math.isclose(lerp(10.0, 20.0, 0.5), 15.0)


def test_circle_points_count_and_radius():
    pts = circle_points(2.5, 12)
    assert len(pts) == 12
    for (x, y) in pts:
        assert math.isclose(math.hypot(x, y), 2.5, rel_tol=1e-12)


def test_circle_points_start_at_phase_and_run_ccw():
    pts = circle_points(1.0, 4)
    assert math.isclose(pts[0][0], 1.0) and math.isclose(pts[0][1], 0.0, abs_tol=1e-12)
    # Counter-clockwise: the second point is at +90 degrees, not -90.
    assert math.isclose(pts[1][0], 0.0, abs_tol=1e-12) and math.isclose(pts[1][1], 1.0)
    phased = circle_points(1.0, 4, phase=math.pi / 2.0)
    assert math.isclose(phased[0][0], 0.0, abs_tol=1e-12) and math.isclose(phased[0][1], 1.0)


def test_circle_points_is_deterministic():
    # The mesh set is regenerated byte-for-byte as a regression check; point ORDER is part of that.
    assert circle_points(3.0, 9) == circle_points(3.0, 9)


def test_circle_points_rejects_degenerate_segment_counts():
    for bad in (-1, 0, 1, 2):
        try:
            circle_points(1.0, bad)
        except ValueError:
            continue
        raise AssertionError(f"circle_points accepted segments={bad}")
