# SPDX-FileCopyrightText: Contributors to fl-base-pack
# SPDX-License-Identifier: CC-BY-4.0
"""Procedural F-16A skin textures — base-colour + ORM PNG masters.

Same rationale and pipeline as the F-5E's (see aircraft/f5e/f5e_textures.py): GENERATED by a
committed, deterministic script, so there is no external image to license or vet under the
likeness policy, and no markings of any kind (policy §4 — generic scheme, no insignia, no
manufacturer marks). The panel layout is a plausible engineering grid matching f16a_build.py's
feature stations, not a copy of any drawing.

Products (into aircraft/f16a/textures-src/):
  f16a_diffuse.png  detail/weathering map in [0,1] modulating the mesh's grey baseColorFactor
  f16a_orm.png      occlusion(R)/roughness(G)/metallic(B), linear, per the engine ORM convention

tex-compress (release.yml) turns these into textures/f16a_{diffuse,orm}.ktx2 at release time.

UV space (fl_meshlib.uvatlas.planar_uvs): u = x/LENGTH nose→tail, v = span port→starboard,
top-down planar (top/bottom shared) — the same placeholder mapping the F-5E ships with.

    python aircraft/f16a/f16a_textures.py           # writes the two PNG masters
    python aircraft/f16a/f16a_textures.py --check   # regenerate in memory and diff (no writes)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
from PIL import Image

RES = 1024
OUT_DIR = Path(__file__).resolve().parent / "textures-src"

# Feature stations in u (x/LENGTH), matching f16a_build.py geometry.
CANOPY_U = (0.125, 0.305)
ANTIGLARE_U = (0.06, 0.125)          # matte shield on the nose, ahead of the windscreen
FRAME_U = [0.10, 0.19, 0.30, 0.40, 0.50, 0.62, 0.74, 0.86, 0.94]  # lateral fuselage frames
STRINGER_V = [0.5, 0.40, 0.60, 0.22, 0.78]                         # longitudinal panel lines
INLET_U = (0.295, 0.56)              # ventral inlet cowl span, darkened lip/duct region


def _uv_grids():
    u = np.linspace(0.0, 1.0, RES, dtype=np.float64)[None, :].repeat(RES, axis=0)
    v = np.linspace(0.0, 1.0, RES, dtype=np.float64)[:, None].repeat(RES, axis=1)
    return u, v


def _line(coord, center, half_width):
    d = np.abs(coord - center)
    return np.clip(1.0 - d / half_width, 0.0, 1.0) ** 2


def _rect(u, v, u0, u1, v0, v1, soft=0.01):
    mu = np.clip((u - u0) / soft, 0, 1) * np.clip((u1 - u) / soft, 0, 1)
    mv = np.clip((v - v0) / soft, 0, 1) * np.clip((v1 - v) / soft, 0, 1)
    return mu * mv


def _panel_lines(u, v):
    m = np.zeros((RES, RES))
    hw = 1.2 / RES
    for fu in FRAME_U:
        m = np.maximum(m, _line(u, fu, hw))
    for sv in STRINGER_V:
        m = np.maximum(m, _line(v, sv, hw))
    # Strake/wing leading-edge seam, running diagonally aft-outboard from the strake apex.
    for sgn in (-1.0, 1.0):
        seam_v = 0.5 + sgn * (0.04 + np.clip((u - 0.26), 0, 1) * 0.55)
        m = np.maximum(m, _line(v, seam_v, hw * 1.4) * (u > 0.26) * (u < 0.82))
    return m


def _weathering(u, v, rng):
    """Grime + the SINGLE-engine exhaust plume (narrower than the F-5E's twin stain)."""
    coarse = rng.random((16, 16))
    blotch = np.asarray(Image.fromarray((coarse * 255).astype(np.uint8)).resize((RES, RES), Image.BICUBIC),
                        dtype=np.float64) / 255.0
    blotch = (blotch - 0.5) * 0.10
    exhaust = np.clip((u - 0.84) / 0.14, 0, 1) ** 1.5 * np.clip(1.0 - np.abs(v - 0.5) / 0.16, 0, 1) * 0.24
    streak = (np.sin(v * np.pi * 220.0) * 0.5 + 0.5) * np.clip((u - 0.2), 0, 1) * 0.015
    # Inlet lip / duct shadow band on the belly projection.
    inlet = _rect(u, v, INLET_U[0], INLET_U[0] + 0.05, 0.42, 0.58, soft=0.012) * 0.30
    return blotch - exhaust - streak - inlet


def build_diffuse(rng) -> np.ndarray:
    u, v = _uv_grids()
    d = np.ones((RES, RES))
    d -= _panel_lines(u, v) * 0.28
    d += _weathering(u, v, rng)
    d -= _rect(u, v, *ANTIGLARE_U, 0.42, 0.58, soft=0.015) * 0.42
    # The F-16's two-grey air-superiority scheme: a slightly darker field over the spine/wing
    # centre section, pure tone elsewhere. Generic — no unit, no insignia, no numbers.
    d -= _rect(u, v, 0.30, 0.86, 0.34, 0.66, soft=0.06) * 0.06
    d += rng.normal(0.0, 0.012, (RES, RES))
    d = np.clip(d, 0.55, 1.0)
    rgb = np.repeat(d[:, :, None], 3, axis=2)
    return (np.clip(rgb, 0, 1) * 255.0 + 0.5).astype(np.uint8)


def build_orm(rng) -> np.ndarray:
    u, v = _uv_grids()
    lines = _panel_lines(u, v)
    ao = np.clip(1.0 - lines * 0.30, 0.0, 1.0)
    worn = np.asarray(Image.fromarray((rng.random((12, 12)) * 255).astype(np.uint8)).resize((RES, RES), Image.BICUBIC),
                      dtype=np.float64) / 255.0
    rough = np.clip(0.94 - (worn - 0.5) * 0.18, 0.75, 1.0)
    rough = np.maximum(rough, _rect(u, v, *ANTIGLARE_U, 0.42, 0.58, soft=0.015))
    metal = np.full((RES, RES), 1.0)
    orm = np.stack([ao, rough, metal], axis=2)
    return (np.clip(orm, 0, 1) * 255.0 + 0.5).astype(np.uint8)


def _generate():
    # Distinct seeds from the F-5E's (51/52) so the two jets' noise fields differ.
    return build_diffuse(np.random.default_rng(61)), build_orm(np.random.default_rng(62))


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate the F-16A procedural skin textures.")
    ap.add_argument("--check", action="store_true",
                    help="regenerate and diff against the committed PNG masters; write nothing")
    args = ap.parse_args()

    diffuse, orm = _generate()

    if args.check:
        drift = 0
        for name, arr in (("f16a_diffuse", diffuse), ("f16a_orm", orm)):
            path = OUT_DIR / f"{name}.png"
            if not path.exists():
                print(f"MISSING: {name}.png", file=sys.stderr)
                drift = 1
                continue
            committed = np.asarray(Image.open(path).convert("RGB"))
            if committed.shape != arr.shape or not np.array_equal(committed, arr):
                print(f"DRIFT: {name}.png differs from the committed master", file=sys.stderr)
                drift = 1
            else:
                print(f"  {name}.png ok")
        return drift

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, arr in (("f16a_diffuse", diffuse), ("f16a_orm", orm)):
        Image.fromarray(arr, "RGB").save(OUT_DIR / f"{name}.png")
        print(f"  {name}.png  ({RES}x{RES})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
