# SPDX-FileCopyrightText: Contributors to fl-base-pack
# SPDX-License-Identifier: CC-BY-4.0
"""Procedural T-38A skin textures — base-colour + ORM PNG masters.

Forked from aircraft/f5e/f5e_textures.py (same method, same UV space); only the feature stations
change to match the T-38 geometry (a longer two-seat tandem canopy, no wingtip rails). WHY
PROCEDURAL: like the mesh, the skin is GENERATED by a committed deterministic script rather than
painted from reference, so the provenance is trivially clean (no external image to license under
docs/legal/aircraft-likeness.md) and it stays regenerable. No photograph is traced; the panel layout
is a plausible engineering grid, not a copy of any drawing.

The pack ships a generic clean GREY scheme (policy §4, no liveries) -- not the real T-38's usual
high-visibility white. See the entity def's `visual` signature note.

WHAT IT PRODUCES (into aircraft/t38a/textures-src/, the committed PNG masters):
  t38a_diffuse.png  base colour — a DETAIL/weathering map in [0,1] that MODULATES the mesh material's
                    grey baseColorFactor. White = full grey, darker = panel lines, anti-glare shield,
                    exhaust staining.
  t38a_orm.png      occlusion (R) / roughness (G) / metallic (B), linear, per the engine's ORM
                    convention (#833).

The tex-compress step turns these into textures/t38a_diffuse.ktx2 / t38a_orm.ktx2 (gitignored build
artifacts). UV space (fl_meshlib.uvatlas.planar_uvs): u = x/LENGTH (0 nose -> 1 tail),
v = (y + SPAN/2)/SPAN. Top-down planar projection; adequate placeholder mapping.

    python aircraft/t38a/t38a_textures.py            # writes the two PNG masters
    python aircraft/t38a/t38a_textures.py --check     # regenerate to memory and diff (no writes)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
from PIL import Image

RES = 1024
OUT_DIR = Path(__file__).resolve().parent / "textures-src"

# Fuselage / feature stations in u (x/LENGTH), matching t38a_build.py geometry.
CANOPY_U = (0.235, 0.420)             # the long two-seat tandem canopy
ANTIGLARE_U = (0.19, 0.235)           # matte shield just forward of the front windscreen
FRAME_U = [0.14, 0.20, 0.30, 0.42, 0.52, 0.66, 0.80, 0.90]  # lateral fuselage frames
STRINGER_V = [0.5, 0.375, 0.625, 0.17, 0.83]                # longitudinal panel lines


def _uv_grids():
    """u across columns (length), v down rows (span) — both in [0,1]."""
    u = np.linspace(0.0, 1.0, RES, dtype=np.float64)[None, :].repeat(RES, axis=0)
    v = np.linspace(0.0, 1.0, RES, dtype=np.float64)[:, None].repeat(RES, axis=1)
    return u, v


def _line(coord, center, half_width):
    """Soft line mask (1 on the line → 0 off it) at |coord-center| < half_width, smooth edges."""
    d = np.abs(coord - center)
    return np.clip(1.0 - d / half_width, 0.0, 1.0) ** 2


def _rect(u, v, u0, u1, v0, v1, soft=0.01):
    """Soft-edged rectangle mask in UV."""
    mu = np.clip((u - u0) / soft, 0, 1) * np.clip((u1 - u) / soft, 0, 1)
    mv = np.clip((v - v0) / soft, 0, 1) * np.clip((v1 - v) / soft, 0, 1)
    return mu * mv


def _panel_lines(u, v):
    """Accumulated panel-line mask (0..1): lateral frames + longitudinal stringers + wing edges."""
    m = np.zeros((RES, RES))
    hw = 1.2 / RES  # ~1.2 px half-width
    for fu in FRAME_U:
        m = np.maximum(m, _line(u, fu, hw))
    for sv in STRINGER_V:
        m = np.maximum(m, _line(v, sv, hw))
    # Wing trailing-edge control-surface line (aileron/flap hinge), spanwise across the wing box.
    wing = _rect(u, v, 0.50, 0.70, 0.0, 1.0, soft=0.02)
    m = np.maximum(m, _line(u, 0.66, hw) * wing)
    return np.clip(m, 0.0, 1.0)


def _weathering(u, v, rng):
    """Low-frequency grime + chordwise streaks + exhaust staining toward the tail. 0 = clean."""
    coarse = rng.random((16, 16))
    blotch = np.asarray(Image.fromarray((coarse * 255).astype(np.uint8)).resize((RES, RES), Image.BICUBIC),
                        dtype=np.float64) / 255.0
    blotch = (blotch - 0.5) * 0.10
    # Exhaust staining: ramps in over the aft fuselage/nozzles (u > 0.82), centred on the body.
    exhaust = np.clip((u - 0.82) / 0.16, 0, 1) ** 1.5 * np.clip(1.0 - np.abs(v - 0.5) / 0.26, 0, 1) * 0.20
    # Faint chordwise (along-u) streaks behind frames.
    streak = (np.sin(v * np.pi * 220.0) * 0.5 + 0.5) * np.clip((u - 0.2), 0, 1) * 0.015
    return blotch - exhaust - streak


def build_diffuse(rng) -> np.ndarray:
    """Detail map in [0,1] modulating the grey baseColorFactor. Returns HxWx3 uint8 (sRGB)."""
    u, v = _uv_grids()
    d = np.ones((RES, RES))
    d -= _panel_lines(u, v) * 0.28                       # panel lines darken to ~0.72
    d += _weathering(u, v, rng)                           # grime/exhaust/streaks
    d -= _rect(u, v, *ANTIGLARE_U, 0.40, 0.60, soft=0.015) * 0.42  # matte anti-glare shield ~0.58
    d += rng.normal(0.0, 0.012, (RES, RES))               # fine surface tooth
    d = np.clip(d, 0.55, 1.0)
    rgb = np.repeat(d[:, :, None], 3, axis=2)
    return (np.clip(rgb, 0, 1) * 255.0 + 0.5).astype(np.uint8)


def build_orm(rng) -> np.ndarray:
    """occlusion(R)/roughness(G)/metallic(B) in [0,1]. Returns HxWx3 uint8 (linear)."""
    u, v = _uv_grids()
    lines = _panel_lines(u, v)
    ao = np.clip(1.0 - lines * 0.30, 0.0, 1.0)             # contact shadow in panel gaps
    worn = np.asarray(Image.fromarray((rng.random((12, 12)) * 255).astype(np.uint8)).resize((RES, RES), Image.BICUBIC),
                      dtype=np.float64) / 255.0
    rough = np.clip(0.94 - (worn - 0.5) * 0.18, 0.75, 1.0)
    rough = np.maximum(rough, _rect(u, v, *ANTIGLARE_U, 0.40, 0.60, soft=0.015))  # matte shield → 1.0
    metal = np.full((RES, RES), 1.0)                       # × material 0.15 = lightly metallic paint
    orm = np.stack([ao, rough, metal], axis=2)
    return (np.clip(orm, 0, 1) * 255.0 + 0.5).astype(np.uint8)


def _generate():
    # Separate seeds so the two maps' noise is independent but each is deterministic.
    return build_diffuse(np.random.default_rng(53)), build_orm(np.random.default_rng(54))


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate the T-38A procedural skin textures.")
    ap.add_argument("--check", action="store_true",
                    help="regenerate and diff against the committed PNG masters; write nothing")
    args = ap.parse_args()

    diffuse, orm = _generate()

    if args.check:
        drift = 0
        for name, arr in (("t38a_diffuse", diffuse), ("t38a_orm", orm)):
            path = OUT_DIR / f"{name}.png"
            if not path.exists():
                print(f"MISSING: {name}.png", file=sys.stderr)
                drift = 1
                continue
            committed = np.asarray(Image.open(path).convert("RGB"))
            if committed.shape != arr.shape or not np.array_equal(committed, arr):
                print(f"DRIFT: {name}.png differs from the committed master", file=sys.stderr)
                drift = 1
            else:
                print(f"  {name}.png ok")
        return drift

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, arr in (("t38a_diffuse", diffuse), ("t38a_orm", orm)):
        Image.fromarray(arr, "RGB").save(OUT_DIR / f"{name}.png")
        print(f"  {name}.png  ({RES}x{RES})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
